version: '3.4'

x-logging:
  &default-logging
  options:
    max-size: '50m'
    max-file: '10'
  driver: json-file

services:

    mongo:
        restart: always
        logging: *default-logging
        image: mongo:4.0
        entrypoint: mongod --smallfiles --bind_ip "0.0.0.0" --wiredTigerCacheSizeGB 0.25
        volumes:
            - ./mongo_data:/data/db

    redis:
        restart: always
        logging: *default-logging
        image: redis:5.0
        volumes:
            - ./redis_data:/data
            
    sharelatex:
        restart: always
        logging: *default-logging
        image: brunneis/sharelatex
        container_name: sharelatex
        depends_on:
            - mongo
            - redis
        ports:
            - 80:80
        volumes:
            - ./sharelatex_data:/var/lib/sharelatex
        environment:
            SHARELATEX_MONGO_URL: mongodb://mongo/sharelatex
            SHARELATEX_REDIS_HOST: redis
            SHARELATEX_APP_NAME: Our ShareLaTeX
            # SHARELATEX_SITE_URL: http://sharelatex.mydomain.com
            # SHARELATEX_NAV_TITLE: Our ShareLaTeX Instance
            # SHARELATEX_HEADER_IMAGE_URL: http://somewhere.com/mylogo.png
            # SHARELATEX_ADMIN_EMAIL: support@it.com
            # SHARELATEX_LEFT_FOOTER: '[{"text": "Powered by <a href=\"https://www.sharelatex.com\">ShareLaTeX</a> 2016"},{"text": "Another page I want to link to can be found <a href=\"here\">here</a>"} ]'
            # SHARELATEX_RIGHT_FOOTER: '[{"text": "Hello I am on the Right"} ]'
            # SHARELATEX_EMAIL_FROM_ADDRESS: "team@sharelatex.com"
            # SHARELATEX_EMAIL_AWS_SES_ACCESS_KEY_ID: 
            # SHARELATEX_EMAIL_AWS_SES_SECRET_KEY: 
            # SHARELATEX_EMAIL_SMTP_HOST: smtp.mydomain.com
            # SHARELATEX_EMAIL_SMTP_PORT: 587
            # SHARELATEX_EMAIL_SMTP_SECURE: false
            # SHARELATEX_EMAIL_SMTP_USER: 
            # SHARELATEX_EMAIL_SMTP_PASS: 
            # SHARELATEX_EMAIL_SMTP_TLS_REJECT_UNAUTH: true
            # SHARELATEX_EMAIL_SMTP_IGNORE_TLS: false
            # SHARELATEX_CUSTOM_EMAIL_FOOTER: "<div>This system is run by department x </div>"

